spring.application.name=catalog-service
server.port=9001
server.tomcat.connection-timeout=2000
server.tomcat.keep-alive-timeout=15000
server.tomcat.threads.max=50
server.tomcat.threads.min-spare=5

spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.uri=http://localhost:8888
spring.cloud.config.request-connect-timeout=5000
spring.cloud.config.request-read-timeout=5000
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.initial-interval=1000
spring.cloud.config.max-interval=2000
spring.cloud.config.multiplier=1.1

spring.datasource.username=user
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5432/polardb_catalog

spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.maximum-pool-size=5

management.endpoints..web.exposure.include=refresh