spring.application.name=catalog-service
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.uri=http://localhost:8888
server.port=9001
server.tomcat.connection-timeout=2000
server.tomcat.keep-alive-timeout=15000
server.tomcat.threads.max=50
server.tomcat.threads.min-spare=5
