apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: catalog-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://polar-postgres:5432/polardb_catalog"
            - name: SPRING_PROFILES_ACTIVE
              value: "testdata"
#            - name: SPRING_CONFIG_IMPORT
#              value: "optional:configserver:http://config-service:8888"
#            - name: SPRING_CLOUD_CONFIG_URI
#              value: "http://config-service:8888"
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001"